# Generated by Django 4.0.1 on 2022-02-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_posted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewed_count',
            field=models.IntegerField(default=0),
        ),
    ]
